### ISSUE TITLE
Luccalug - Toscana

### ISSUE THREAD

**Issue by Luccalug** [Gelma/LugMap#17]
Salve, sono il videpresidente di Luccalug, ho notato che siamo stati tolti da LugMap, è possibile essere reinseriti ?
Dobbiamo fare qualcosa per verificare la nostra identità?

**Comment by madbob** [comment]
Il sito e' stato temporaneamente rimosso il 21 giugno durante le periodiche operazioni di revisione, evidentemente all'epoca e' stato trovato offline. L'ho ripristinato ora, dovrebbe tornare online nelle prossime ore.
https://github.com/Gelma/LugMap/commit/8224f8a5a2d02b0a41ae1b22929d1de0dd8acc19

**Comment by BeTmAsTeR** [comment]
Scusa se rompo, ma la nostra associazione si chiama "Luccalug" non "Lucca Lug"

grazie ancora :smile:

**Comment by Luccalug** [comment]
Scusa se rompo ma l'associazione si chiama "Luccalug" non "Lucca Lug"

grazie tante :D
