### ISSUE TITLE
Mappa in modale

### ISSUE THREAD

**Issue by Mte90** [Gelma/LugMap#32]
Invece di aprire un altri link con solo la mappa e la testata forse è più comodo una lightbox o modale con dentro la mappa.

**Comment by valerio-bozzolan** [comment]
Immagino che hai il privilegio di avere un desktop bello largo. Sul mio desktop o su mobile ammetto che troverei la cosa un po' complicata.

**Comment by Mte90** [comment]
Il problema ha senso ma ritrovarsi con un refresh ecc per avere una pagina con solo la mappa è molto scomodo, è più pratico una modale dove la mappa è bella grande tanto si zoommano sempre.
