### ISSUE TITLE
Pagina eventi da rimuovere

### ISSUE THREAD

**Issue by Mte90** [Gelma/LugMap#33]
https://lugmap.linux.it/eventi/
Questa pagina ha contenuto obsoleto credo dal 2016/2017 forse conviene mettere il link al planet.

**Comment by madbob** [comment]
Rinominato in "Assistenza".

Gli eventi occasionali stanno gia' su Planet, ma qui c'e' rimasta almeno la mappa degli appuntamenti periodici (e.g. sportelli di assistenza) che su Planet non c'e' ne' deve esserci (finirebbe col diventare totalmente inutile da consultare).

Cfr. https://github.com/Gelma/LugMap/commit/0b37562c1791aee024aa04e48a534402b5c1dbd7
